import { expect, test, type APIRequestContext, type Page, type TestInfo } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';

const api = process.env.ROOMIES_API_URL ?? 'http://localhost:8080/api';
const web = process.env.ROOMIES_WEB_URL ?? 'http://localhost';
const evidence = new WeakMap<Page, { console: string[]; page: string[]; failed: string[] }>();
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-');
test.beforeEach(async ({ page }) => { const value = { console: [] as string[], page: [] as string[], failed: [] as string[] }; evidence.set(page, value); page.on('console', m => { if (m.type() === 'error') value.console.push(m.text()); }); page.on('pageerror', e => value.page.push(e.message)); page.on('requestfailed', r => value.failed.push(r.url())); });
test.afterEach(async ({ page }, info: TestInfo) => { const value = evidence.get(page)!; const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth); await mkdir('artifacts/evidence', { recursive: true }); const name = `${info.project.name}-notifications-${slug(info.title)}`; await page.screenshot({ path: `artifacts/evidence/${name}.png`, fullPage: true }); await writeFile(`artifacts/evidence/${name}.json`, JSON.stringify({ project: info.project.name, test: info.title, consoleErrors: value.console.length, pageErrors: value.page.length, failedRequests: value.failed.length, horizontalOverflow: overflow }, null, 2)); expect(value.console).toEqual([]); expect(value.page).toEqual([]); expect(value.failed).toEqual([]); expect(overflow).toBeFalsy(); });

async function register(request: APIRequestContext, label: string) { const email = `${label}-${Date.now()}-${Math.random().toString(16).slice(2)}@example.test`; const r = await request.post(`${api}/auth/register`, { data: { name: label, email, password: 'synthetic-password-123' } }); expect(r.ok()).toBeTruthy(); return { email, ...(await r.json() as { token: string; user: { id: string } }) }; }
async function house(request: APIRequestContext) { const admin = await register(request, 'Admin'); const r = await request.post(`${api}/houses`, { headers: { Authorization: `Bearer ${admin.token}` }, data: { name: 'Notification House' } }); expect(r.ok()).toBeTruthy(); return { admin, id: (await r.json() as { id: string }).id }; }
async function login(page: Page, email: string) { await page.goto(web); await page.getByPlaceholder('Email').fill(email); await page.getByPlaceholder('Password').fill('synthetic-password-123'); await page.getByRole('button', { name: 'Login' }).click(); await expect(page).toHaveURL(/\/dashboard$/); }
async function notifications(page: Page, id: string) { await page.goto(`${web}/house/${id}`); await page.getByRole('tab', { name: 'Notifications / Schedule' }).click(); await expect(page.getByRole('heading', { name: 'Notifications & schedule' })).toBeVisible(); }

test('preferences reload and public VAPID unavailable state are explicit', async ({ page, request }) => { const data = await house(request); await login(page, data.admin.email); await notifications(page, data.id); await page.getByLabel('Shared expense alerts').uncheck(); await page.getByRole('button', { name: 'Save preferences' }).click(); await expect(page.getByText('Notification preferences saved.')).toBeVisible(); await page.reload(); await page.getByRole('tab', { name: 'Notifications / Schedule' }).click(); await expect(page.getByLabel('Shared expense alerts')).not.toBeChecked(); const key = await request.get(`${api}/notifications/vapid-public-key`); expect(key.ok()).toBeTruthy(); expect((await key.json()).public_key).toBe(''); const sw = await page.request.get(`${web}/roomies-sw.js`); expect(sw.ok()).toBeTruthy(); await page.getByRole('button', { name: 'Enable browser push' }).click(); await expect(page.getByText('Browser push is not configured by this server.')).toBeVisible(); });

test('member creates edits and deletes a scheduled event', async ({ page, request }) => { const data = await house(request); const member = await register(request, 'Member'); const joined = await request.post(`${api}/houses/${data.id}/members`, { headers: { Authorization: `Bearer ${data.admin.token}` }, data: { user_id: member.user.id, role: 'member' } }); expect(joined.ok()).toBeTruthy(); await login(page, member.email); await notifications(page, data.id); await page.getByLabel('Title').fill('Bins'); await page.getByLabel('Local start').fill('2025-02-01T09:00'); await page.getByRole('button', { name: 'Create scheduled event' }).click(); await expect(page.getByText('Scheduled event created.')).toBeVisible(); await page.getByRole('button', { name: 'Edit' }).click(); await expect(page.getByRole('heading', { name: 'Edit scheduled event' })).toBeVisible(); await page.getByLabel('Title').fill('Recycling'); await page.getByRole('button', { name: 'Save scheduled event' }).click(); await expect(page.getByText('Scheduled event updated.')).toBeVisible(); await expect(page.getByText('Recycling')).toBeVisible(); await page.getByRole('button', { name: 'Delete' }).click(); await expect(page.getByText('Event deleted; refresh this tab to update the list.')).toBeVisible(); });

test('monitor is view-only and recurrence feedback is local', async ({ page, request }) => { const data = await house(request); const monitor = await register(request, 'Monitor'); const joined = await request.post(`${api}/houses/${data.id}/members`, { headers: { Authorization: `Bearer ${data.admin.token}` }, data: { user_id: monitor.user.id, role: 'monitor' } }); expect(joined.ok()).toBeTruthy(); await login(page, monitor.email); await notifications(page, data.id); await expect(page.getByText('Monitors can view scheduled events but cannot create, edit, or delete them.')).toBeVisible(); await expect(page.getByRole('button', { name: 'Create scheduled event' })).toHaveCount(0); });

test('invalid recurrence and EXDATE receive local feedback', async ({ page, request }) => { const data = await house(request); await login(page, data.admin.email); await notifications(page, data.id); await page.getByLabel('Title').fill('Bins'); await page.getByLabel('Local start').fill('2025-02-01T09:00'); await page.getByLabel('Interval (1–366)').fill('367'); await page.getByRole('button', { name: 'Create scheduled event' }).click(); await expect(page.getByText('Interval must be 1–366.')).toBeVisible(); await page.getByLabel('Interval (1–366)').fill('1'); await page.getByLabel('EXDATE local times (comma-separated)').fill(Array.from({ length: 101 }, (_, i) => `2025-02-${String((i % 28) + 1).padStart(2, '0')}T09:00`).join(',')); await page.getByRole('button', { name: 'Create scheduled event' }).click(); await expect(page.getByText('At most 100 exception dates are allowed.')).toBeVisible(); });
