[workspace]
members = ["src/app"]
exclude = ["vendor/android-native-keyring-store"]
resolver = "2"

[patch.crates-io]
android-native-keyring-store = { path = "vendor/android-native-keyring-store" }

[profile.release]
opt-level = "s"
lto = true

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
